### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by toverux** [MacSergey/ModsCommon#50]
Hi!

I stumbled upon your shared helper library while learning to create C:S mods and liked it. However there is no licensing information so I'm not sure I'm able to use it in my own mod (theoretically, no). Therefore I hereby request permission to use it, as well as suggest you to add a license.

And since I'm here : thanks for your awesome mods (especially NetworkMultitool/NodeController) and the quality of your code (above standards in the community it seems...).

**Comment by MacSergey** [comment]
You can use it for CS modding

**Comment by toverux** [comment]
Thank you very much!
